name: deploy app to server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_name: registry.digitalocean.com/takhir-registry/my-node-app:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: build and push docker
        working-directory: ./my-node-app
        run: |
          docker build -t registry.digitalocean.com/takhir-registry/my-node-app:${{ github.sha }} .
          docker login registry.digitalocean.com -u takhir.ismailoff@gmail.com -p ${{ secrets.REGISTRY_TOKEN }}
          docker push registry.digitalocean.com/takhir-registry/my-node-app:${{ github.sha }}
          

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./my-node-app/docker-compose-prod.yaml"
          target: "/opt/ci-cd-with-docker/"
          strip_components: 2

      - name: restart docker compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/ci-cd-with-docker
            mv docker-compose-prod.yaml docker-compose.yaml
            docker login registry.digitalocean.com -u takhir.ismailoff@gmail.com -p ${{ secrets.REGISTRY_TOKEN }}
            yq -i '.services.web.image = "${{ needs.build.outputs.image_name }}"' docker-compose.yaml
            docker compose up -d --remove-orphans
        
          
