name: deploy app to server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v4

      - name: copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./django_app"
          target: /opt/

      - name: Execute remote SSH commands using key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/django_app
            python3 -m venv myvenv
            source myvenv/bin/activate
            pip3 install -r requirements.txt
            python3 manage.py collectstatic --noinput
            python3 manage.py migrate
            sudo systemctl restart django-app